[package]
name = "marionette-example"
version = "0.1.0"
edition = "2021"


[dependencies]
libc = "0.2"

[toolchain]
channel = "nightly"


[features]
default = ["regular"]
regular = []
instrumented = []